framework:
    messenger:
        failure_transport: failed
        transports:
            async:
                dsn: 'doctrine://default'
                options:
                    auto_setup: true
            failed:
                dsn: 'doctrine://default?queue_name=failed'
                options:
                    auto_setup: true

        default_bus: messenger.bus.default
        buses:
            messenger.bus.default: []

        routing:
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': async
            'Symfony\Component\Notifier\Message\ChatMessage': async
            'Symfony\Component\Notifier\Message\SmsMessage': async








