# config/packages/security.yaml
security:
    # Configuración para el hash de contraseñas
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Configuración del proveedor de usuarios basado en entidad
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Usuario
                property: email  # Asumiendo que el email es único y usado para login

    # Configuración de firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            entry_point: App\Security\AppLoginAuthenticator
            # Formulario de login
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: /post_login
                username_parameter: email
                password_parameter: password

            # Configuración de logout
            logout:
                path: app_logout
                target: app_login  # Redirige aquí después del logout

            # Personalizado en lugar de 'form_login' 
            # custom_authenticator: App\Security\AppLoginAuthenticator

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800  # 1 semana
                path: /
                # Uncomment the following line to always enable remember_me feature.
                # always_remember_me: true

            
            
    # Control de acceso
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/cancelar/\d+$, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4  # Coste más bajo posible para bcrypt
                time_cost: 3  # Coste de tiempo más bajo para argon
                memory_cost: 10  # Coste de memoria más bajo para argon


