controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_login
        permanent: true

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

send_test_email:
    path: /test-email
    controller: App\Controller\EmailTestController::sendTestEmail
